name: 'nix-deadnix-action'
description: 'Find and remove unused Nix code, then commit and push the changes'

inputs:
  flags:
    description: 'Command-line flags to deadnix'
    required: false
    default: '--edit'
  author:
    description: 'Author name and email in the format `Name <email@address.com>`'
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  committer:
    description: 'Committer name and email'
    required: false
    default: 'GitHub <noreply@github.com>'
  directory:
    description: 'Directory to scan for dead Nix code'
    required: false
    default: '.'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Chore: Automated dead code cleanup'
  exclude:
    description: 'Path to exclude from deadnix scanning (optional)'
    required: false
  open_pr:
    description: 'Whether to create a pull request instead of pushing to the current branch'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run deadnix
      shell: bash
      id: deadnix
      run: |
        EXCLUDE_OPTION=""
        if [ -n "${{ inputs.exclude }}" ]; then
          EXCLUDE_OPTION="--exclude ${{ inputs.exclude }}"
        fi
        nix run nixpkgs#deadnix -- ${{ inputs.flags }} ${{ inputs.directory }} $EXCLUDE_OPTION

    - name: Commit and push changes or open PR
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name "${{ inputs.author }}"
        git config --global user.email "${{ inputs.author }}"

        git add .
        git diff --staged --quiet && echo "No changes to commit" && exit 0

        git commit -m "${{ inputs.commit_message }}"

        if [ "${{ inputs.open_pr }}" = "true" ]; then
          BRANCH="deadnix-fix-$(date +%s)"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"

          gh pr create \
            --title "${{ inputs.commit_message }}" \
            --body "This PR was automatically generated by nix-deadnix-action to remove dead Nix code." \
            --head "$BRANCH" \
            --base "${{ github.ref_name }}"
        else
          git push origin HEAD:${{ github.ref_name }}
        fi

branding:
  icon: 'upload-cloud'
  color: 'blue'
