name: 'nix-deadnix-action'
description: 'Find and remove unused Nix code, then commit and push the changes'

inputs:
  flags:
    description: 'Command-line flags to deadnix'
    required: false
    default: '--edit'
  author:
    description: 'Author name and email in the format `Name <email@address.com>`'
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  committer:
    description: 'Committer name and email'
    required: false
    default: 'GitHub <noreply@github.com>'
  directory:
    description: 'Directory to scan for dead Nix code'
    required: false
    default: '.'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Chore: Remove dead Nix code'
  exclude:
    description: 'Path to exclude from deadnix scanning (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run deadnix
      shell: bash
      id: deadnix
      run: |
        EXCLUDE_OPTION=""
        if [ -n "${{ inputs.exclude }}" ]; then
          EXCLUDE_OPTION="--exclude ${{ inputs.exclude }}"
        fi
        nix run nixpkgs#deadnix -- ${{ inputs.flags }} ${{ inputs.directory }} $EXCLUDE_OPTION

    - name: Commit and push changes
      shell: bash
      run: |
        git config --global user.name "${{ inputs.author }}"
        git config --global user.email "${{ inputs.author }}"
        git add .
        git commit -m "${{ inputs.commit_message }}" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }}

branding:
  icon: 'upload-cloud'
  color: 'blue'
